version: "3.3"
services: 
  product-page:
    container_name: 44-productpage
    image: 44/productpage
    build: ./product-page
    ports: 
      - 9080:9080
    environment: 
      - DETAILS_HOSTNAME=details
      - RATINGS_HOSTNAME=ratings
      - REVIEWS_HOSTNAME=reviews
      - GROUP_NUMBER=Equipo 44 
      - ENABLE_RATINGS=true
  details:
    container_name: 44-details
    image: 44/details
    build: ./details
  reviews:
    container_name: 44-reviews
    image: 44/reviews
    build: ./reviews
    environment:
      - RATINGS_HOSTNAME=ratings
      - ENABLE_RATINGS=true
      - SERVICE_VERSION=v3
  ratings:
    container_name: 44-ratings
    image: 44/ratings
    build: ./ratings
    environment:
      - SERVICE_VERSION=v1
